# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CountNbd <- function(Rr, Rx, Ry, RWeight, RNbd, RIsReferenceType, RIsNeighborType) {
    invisible(.Call('dbmss_CountNbd', PACKAGE = 'dbmss', Rr, Rx, Ry, RWeight, RNbd, RIsReferenceType, RIsNeighborType))
}

CountNbdCC <- function(Rr, Rx, Ry, RWeight, RNbd, RIsReferenceType, RIsNeighborType) {
    invisible(.Call('dbmss_CountNbdCC', PACKAGE = 'dbmss', Rr, Rx, Ry, RWeight, RNbd, RIsReferenceType, RIsNeighborType))
}

DistKd <- function(Rx, Ry, RPointWeight, RWeights, RDist, RIsReferenceType, RIsNeighborType) {
    invisible(.Call('dbmss_DistKd', PACKAGE = 'dbmss', Rx, Ry, RPointWeight, RWeights, RDist, RIsReferenceType, RIsNeighborType))
}

